chore(dev): update typescript
this showed the error before the previous commit as

```
test/types.ts:16:7 - error TS2345: Argument of type '{ query: string; }' is not assignable to parameter of type 'PlainSearchParameters'.
  Object literal may only specify known properties, and 'query' does not exist in type 'PlainSearchParameters'.

16       query: 'something fun',
         ~~~~~

Found 1 error in test/types.ts:16

error Command failed with exit code 2.
```